### ISSUE TITLE
object has no init args

### ISSUE THREAD

**Issue by DocBO** [darkanthey/oauth2-stateless#1]
Hi,
congrats for your nice project.

I received an error when playing around with AuthorizationCodeGrant.

In grant.py line 373 super(SiteAdapterMixin, self).__init__(**kwargs)
leads to an error when using e.g. 
~~~~
AuthorizationCodeGrant(unique_token=True, expires_in=20)
~~~~
Imho should be: 
~~~~
super(SiteAdapterMixin, self).__init__() 
~~~~
or no init call at all, since object is the superclass of SiteAdapterMixin.

Another question: you have nowhere an example how to check the validity of the token if the client need resource from the server. I read some of the API and I think it can be done with the token_store. Is this the way how it should be done?

somehwere in the server, after receiving a token to be checked against existing database

~~~~
try:
    token_data = self.token_store.fetch_by_token(token) 
    answer = "%s %s" % (token_data.user_id, token_data.is_expired())
except:
    ....
~~~~

**Comment by darkanthey** [comment]
Many thanks DocBO I'll fix it thank you for the hint.

**Comment by DocBO** [comment]
Hey cool, thought the project is maybe dead but no, it's alive !!!
If I need it in future I will use it and maybe contribute to it.

**Comment by darkanthey** [comment]
Project fully alive. I'm solving my personal problem.

So I added some example. When you provide "AuthorizationCodeGrant(unique_token=True"
That's mean you should return user_id in "authenticate" method.

You can check it in oauth2/web/__init__ class AuthenticatingSiteAdapter(object)
        :return: A ``dict`` containing arbitrary data that will be passed to
                 the current storage adapter and saved with auth code and
                 access token. Return a tuple in the form
                 `(additional_data, user_id)` if you want to use
                 :doc:`unique_token`.

**Comment by darkanthey** [comment]
And yes, sorry I have to remove PY2 support. Time to moving forward. PY2 will deprecated soon.
