### ISSUE TITLE
Grant Type not supported in aiohttp example

### ISSUE THREAD

**Issue by thebpmgroup** [darkanthey/oauth2-stateless#2]
Running the aiohttp example, but instead of using the client app trying to wind it through by hand using a browser and or Postman. Just trying to get my head around the process.

I believe I want a 3 legged oAuth2 flow with Authorization Code Grant, which it looks like the example is doing.

I get the authorization code by following the url in the browser :

> http://localhost:8083/authorize?client_id=abc&redirect_uri=http://localhost:8084/callback&response_type=code

This serves the page with the confirm and or deny links, and clicking confirm then calls back to :

> http://localhost:8084/callback?code=c2daa5a6-3cb3-446a-a4d9-b39558b1a7b4

Which is great as I now have my authorization code.

So now I want to request a token, but when I try I get the following error : 

> {
>    "error": "unsupported_response_type",
>    "error_description": "Grant not supported"
> }

Which is weird as I am supplying the grant type as per the example as "**code**".

> localhost:8083/token?client_id=123&client_secret=xyz&code=ab7031b2-5153-4772-b640-6ad112f75024&grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%3A8083%2Fcallback

What am I doing wrong?

**Comment by thebpmgroup** [comment]
I have managed to get it working by using a form post in Postman. It seems from the code supports only form data and not JSON for the POST method. It works well once you do this. :)

**Comment by darkanthey** [comment]
This lib using post form instead of JSON.
